point_values = { 
    "city_stats": {
        "population": {
            0: 0,
            200000: 5,
            300000: 10, 
            400000: 10, 
            500000: 10,
            750000: 10,
            1000000: 10,
            1500000: 10,
            2000000: 10,
            2500000: 10,
            3000000: 10,
            4000000: 10,
            5000000: 10,
            7500000: 10,
            10000000: 10,
            20000000: 10,
            30000000: 10
        },
        "lang_1": {
            "Acehnese": 0,
            "Acholi": 0,
            "Afaan Oromoo": 0,
            "Afrikaans": 2,
            "Akan": 0,
            "Albanian": 2,
            "Ambonese Malay": 0,
            "Amharic": 0,
            "Arabic": 4,
            "Armenian": 2,
            "Assamese": 2,
            "Avar": 0,
            "Azerbaijani": 2,
            "Bahasa Indonesia": 0,
            "Balochi": 0,
            "Bambara": 0,
            "Banjar": 0,
            "Bari": 0,
            "Bariba": 0,
            "Bassa": 0,
            "Batak": 0,
            "Beja": 0,
            "Belarusian": 2,
            "Bemba": 0,
            "Bengali": 2,
            "Biak": 0,
            "Bikol": 0,
            "Bosnian": 2,
            "Buginese": 0,
            "Bulgarian": 2,
            "Burmese": 0,
            "Cantonese": 0,
            "Cape Verdean Creole": 0,
            "Catalan": 2,
            "Cebuano": 0,
            "Central Bikol": 0,
            "Central Thai": 0,
            "Chavacano": 0,
            "Chichewa": 0,
            "Chinese (Mandarin)": 0,
            "Chitumbuka": 0,
            "Chokwe": 0,
            "Cinyanja": 0,
            "Cokwe": 0,
            "Comorian (Shikomori)": 0,
            "Creole": 0,
            "Croatian": 2,
            "Czech": 2,
            "Dagbani": 0,
            "Danish": 2,
            "Dari": 0,
            "Dhivehi": 0,
            "Dinka": 0,
            "Diola": 0,
            "Dioula": 0,
            "Dogri": 0,
            "Dutch": 6,
            "Dzongkha": 0,
            "Edo": 0,
            "Efik": 0,
            "Eggon": 0,
            "Egyptian Arabic": 0,
            "Emakhuwa": 0,
            "English": 10,
            "Estonian": 2,
            "Ewe": 0,
            "Fang": 0,
            "Fante": 0,
            "Farsi": 4,
            "Filipino": 0,
            "Finnish": 0,
            "Fon": 0,
            "French": 8,
            "Fulfulde": 0,
            "Galician": 0,
            "Georgian": 0,
            "German": 6,
            "Greek": 2,
            "Guarani": 0,
            "Guaraní": 0,
            "Gujarati": 2,
            "Haitian Creole": 2,
            "Hakka Chinese": 0,
            "Hassaniya Arabic": 0,
            "Hausa": 0,
            "Haya": 0,
            "Hebrew": 0,
            "Hiligaynon": 0,
            "Hiligaynon/Ilonggo": 0,
            "Hindi": 4,
            "Hungarian": 0,
            "Ibibio": 0,
            "Icelandic": 4,
            "Igbo": 0,
            "Ijaw": 0,
            "Ilocano": 0,
            "Ilokano": 0,
            "Indonesian": 0,
            "Ingessana": 0,
            "Italian": 6,
            "Japadhola": 0,
            "Japanese": 0,
            "Javanese": 0,
            "Jingpho": 0,
            "K'iche'": 0,
            "Ka'qchikel": 0,
            "Kabyle": 0,
            "Kalmyk": 0,
            "Kannada": 0,
            "Kanuri": 0,
            "Kapampangan": 0,
            "Kashmiri": 2,
            "Kazakh": 0,
            "Khasi": 0,
            "Khmer": 0,
            "Kikongo": 0,
            "Kimeru": 0,
            "Kinyarwanda": 0,
            "Kirundi": 0,
            "Kissi": 0,
            "Kituba": 0,
            "Korean": 0,
            "Kpelle": 0,
            "Krio": 0,
            "Kurdish": 2,
            "Kwanyama": 0,
            "Kyrgyz": 0,
            "Lamnso'": 0,
            "Lango": 0,
            "Lao": 0,
            "Latvian": 2,
            "Lingala": 0,
            "Lithuanian": 2,
            "Luganda": 0,
            "Lugbara": 0,
            "Lumasaba": 0,
            "Luo": 0,
            "Luri": 0,
            "Macedonian": 2,
            "Maguindanaon": 0,
            "Maithili": 2,
            "Makhuwa": 0,
            "Malagasy": 0,
            "Malay": 0,
            "Malayalam": 0,
            "Malinké": 0,
            "Mandar": 0,
            "Mandarin": 0,
            "Mandarin (Standard Chinese)": 0,
            "Mandarin Chinese": 0,
            "Mandingo": 0,
            "Maninka": 0,
            "Maranao": 0,
            "Marathi": 2,
            "Masalit": 0,
            "Mauritian Creole": 0,
            "Medumba": 0,
            "Meiteilon (Manipuri)": 0,
            "Mende": 0,
            "Minangkabau": 0,
            "Mizo": 0,
            "Mongolian": 0,
            "Montenegrin": 0,
            "Mooré": 0,
            "Nahuatl": 0,
            "Ndebele": 0,
            "Nepali": 2,
            "Nias": 0,
            "Northern Sotho": 0,
            "Norwegian": 2,
            "Odia": 2,
            "Oromo": 0,
            "Pahari-Pothwari": 0,
            "Pangasinan": 0,
            "Pashto": 2,
            "Persian": 4,
            "Persian (Farsi)": 4,
            "Pidgin English": 2,
            "Polish": 2,
            "Portuguese": 6,
            "Pular": 0,
            "Punjabi": 2,
            "Q'eqchi'": 0,
            "Quechua": 0,
            "Rajasthani": 0,
            "Rakhine": 0,
            "Romanian": 4,
            "Russian": 2,
            "Sango": 0,
            "Sar": 0,
            "Sara": 0,
            "Saraiki": 0,
            "Sasak": 0,
            "Sepedi": 0,
            "Serbian": 2,
            "Sesotho": 0,
            "Setswana": 0,
            "Shilluk": 0,
            "Shona": 0,
            "Sikka": 0,
            "Sindhi": 2,
            "Sinhala": 2,
            "Slovak": 2,
            "Slovene": 2,
            "Somali": 0,
            "Spanish": 8,
            "Sukuma": 0,
            "Sundanese": 0,
            "Susue (Susu)": 0,
            "Swahili": 0,
            "Swedish": 2,
            "Sylheti": 0,
            "Tagalog": 0,
            "Tagalog/Filipino": 0,
            "Taishanese (a variety of Yue Chinese)": 0,
            "Tajik": 2,
            "Tamasheq": 0,
            "Tamazight": 0,
            "Tamil": 0,
            "Tausug": 0,
            "Telugu": 0,
            "Tem": 0,
            "Teochew": 0,
            "Thai": 0,
            "Tibetan": 0,
            "Tigrinya": 0,
            "Tiv": 0,
            "Tobelo": 0,
            "Tok Pisin": 0,
            "Tonga": 0,
            "Tshiluba": 0,
            "Tulu": 0,
            "Turkish": 0,
            "Turkmen": 0,
            "Twi": 0,
            "Uighur": 0,
            "Ukrainian": 2,
            "Umbundu": 0,
            "Urdu": 2,
            "Urhobo": 0,
            "Uyghur": 0,
            "Uzbek": 0,
            "Vietnamese": 0,
            "Waray": 0,
            "Waray-Waray": 0,
            "Wayuu": 0,
            "Wenzhounese": 0,
            "Wolof": 0,
            "Xhosa": 0,
            "Yoruba": 0,
            "Zarma/Songhai": 0,
            "Zhuang": 0,
            "Zulu": 0,
            "isiXhosa": 0,
            "isiZulu": 0
        },
        "lang_2": {
            "Acehnese": 0,
            "Acholi": 0,
            "Afaan Oromoo": 0,
            "Afrikaans": 2,
            "Akan": 0,
            "Albanian": 2,
            "Ambonese Malay": 0,
            "Amharic": 0,
            "Arabic": 4,
            "Armenian": 2,
            "Assamese": 2,
            "Avar": 0,
            "Azerbaijani": 2,
            "Bahasa Indonesia": 0,
            "Balochi": 0,
            "Bambara": 0,
            "Banjar": 0,
            "Bari": 0,
            "Bariba": 0,
            "Bassa": 0,
            "Batak": 0,
            "Beja": 0,
            "Belarusian": 2,
            "Bemba": 0,
            "Bengali": 2,
            "Biak": 0,
            "Bikol": 0,
            "Bosnian": 2,
            "Buginese": 0,
            "Bulgarian": 2,
            "Burmese": 0,
            "Cantonese": 0,
            "Cape Verdean Creole": 0,
            "Catalan": 2,
            "Cebuano": 0,
            "Central Bikol": 0,
            "Central Thai": 0,
            "Chavacano": 0,
            "Chichewa": 0,
            "Chinese (Mandarin)": 0,
            "Chitumbuka": 0,
            "Chokwe": 0,
            "Cinyanja": 0,
            "Cokwe": 0,
            "Comorian (Shikomori)": 0,
            "Creole": 0,
            "Croatian": 2,
            "Czech": 2,
            "Dagbani": 0,
            "Danish": 2,
            "Dari": 0,
            "Dhivehi": 0,
            "Dinka": 0,
            "Diola": 0,
            "Dioula": 0,
            "Dogri": 0,
            "Dutch": 6,
            "Dzongkha": 0,
            "Edo": 0,
            "Efik": 0,
            "Eggon": 0,
            "Egyptian Arabic": 0,
            "Emakhuwa": 0,
            "English": 10,
            "Estonian": 2,
            "Ewe": 0,
            "Fang": 0,
            "Fante": 0,
            "Farsi": 4,
            "Filipino": 0,
            "Finnish": 0,
            "Fon": 0,
            "French": 8,
            "Fulfulde": 0,
            "Galician": 0,
            "Georgian": 0,
            "German": 6,
            "Greek": 2,
            "Guarani": 0,
            "Guaraní": 0,
            "Gujarati": 2,
            "Haitian Creole": 2,
            "Hakka Chinese": 0,
            "Hassaniya Arabic": 0,
            "Hausa": 0,
            "Haya": 0,
            "Hebrew": 0,
            "Hiligaynon": 0,
            "Hiligaynon/Ilonggo": 0,
            "Hindi": 4,
            "Hungarian": 0,
            "Ibibio": 0,
            "Icelandic": 4,
            "Igbo": 0,
            "Ijaw": 0,
            "Ilocano": 0,
            "Ilokano": 0,
            "Indonesian": 0,
            "Ingessana": 0,
            "Italian": 6,
            "Japadhola": 0,
            "Japanese": 0,
            "Javanese": 0,
            "Jingpho": 0,
            "K'iche'": 0,
            "Ka'qchikel": 0,
            "Kabyle": 0,
            "Kalmyk": 0,
            "Kannada": 0,
            "Kanuri": 0,
            "Kapampangan": 0,
            "Kashmiri": 2,
            "Kazakh": 0,
            "Khasi": 0,
            "Khmer": 0,
            "Kikongo": 0,
            "Kimeru": 0,
            "Kinyarwanda": 0,
            "Kirundi": 0,
            "Kissi": 0,
            "Kituba": 0,
            "Korean": 0,
            "Kpelle": 0,
            "Krio": 0,
            "Kurdish": 2,
            "Kwanyama": 0,
            "Kyrgyz": 0,
            "Lamnso'": 0,
            "Lango": 0,
            "Lao": 0,
            "Latvian": 2,
            "Lingala": 0,
            "Lithuanian": 2,
            "Luganda": 0,
            "Lugbara": 0,
            "Lumasaba": 0,
            "Luo": 0,
            "Luri": 0,
            "Macedonian": 2,
            "Maguindanaon": 0,
            "Maithili": 2,
            "Makhuwa": 0,
            "Malagasy": 0,
            "Malay": 0,
            "Malayalam": 0,
            "Malinké": 0,
            "Mandar": 0,
            "Mandarin": 0,
            "Mandarin (Standard Chinese)": 0,
            "Mandarin Chinese": 0,
            "Mandingo": 0,
            "Maninka": 0,
            "Maranao": 0,
            "Marathi": 2,
            "Masalit": 0,
            "Mauritian Creole": 0,
            "Medumba": 0,
            "Meiteilon (Manipuri)": 0,
            "Mende": 0,
            "Minangkabau": 0,
            "Mizo": 0,
            "Mongolian": 0,
            "Montenegrin": 0,
            "Mooré": 0,
            "Nahuatl": 0,
            "Ndebele": 0,
            "Nepali": 2,
            "Nias": 0,
            "Northern Sotho": 0,
            "Norwegian": 2,
            "Odia": 2,
            "Oromo": 0,
            "Pahari-Pothwari": 0,
            "Pangasinan": 0,
            "Pashto": 2,
            "Persian": 4,
            "Persian (Farsi)": 4,
            "Pidgin English": 2,
            "Polish": 2,
            "Portuguese": 6,
            "Pular": 0,
            "Punjabi": 2,
            "Q'eqchi'": 0,
            "Quechua": 0,
            "Rajasthani": 0,
            "Rakhine": 0,
            "Romanian": 4,
            "Russian": 2,
            "Sango": 0,
            "Sar": 0,
            "Sara": 0,
            "Saraiki": 0,
            "Sasak": 0,
            "Sepedi": 0,
            "Serbian": 2,
            "Sesotho": 0,
            "Setswana": 0,
            "Shilluk": 0,
            "Shona": 0,
            "Sikka": 0,
            "Sindhi": 2,
            "Sinhala": 2,
            "Slovak": 2,
            "Slovene": 2,
            "Somali": 0,
            "Spanish": 8,
            "Sukuma": 0,
            "Sundanese": 0,
            "Susue (Susu)": 0,
            "Swahili": 0,
            "Swedish": 2,
            "Sylheti": 0,
            "Tagalog": 0,
            "Tagalog/Filipino": 0,
            "Taishanese (a variety of Yue Chinese)": 0,
            "Tajik": 2,
            "Tamasheq": 0,
            "Tamazight": 0,
            "Tamil": 0,
            "Tausug": 0,
            "Telugu": 0,
            "Tem": 0,
            "Teochew": 0,
            "Thai": 0,
            "Tibetan": 0,
            "Tigrinya": 0,
            "Tiv": 0,
            "Tobelo": 0,
            "Tok Pisin": 0,
            "Tonga": 0,
            "Tshiluba": 0,
            "Tulu": 0,
            "Turkish": 0,
            "Turkmen": 0,
            "Twi": 0,
            "Uighur": 0,
            "Ukrainian": 2,
            "Umbundu": 0,
            "Urdu": 2,
            "Urhobo": 0,
            "Uyghur": 0,
            "Uzbek": 0,
            "Vietnamese": 0,
            "Waray": 0,
            "Waray-Waray": 0,
            "Wayuu": 0,
            "Wenzhounese": 0,
            "Wolof": 0,
            "Xhosa": 0,
            "Yoruba": 0,
            "Zarma/Songhai": 0,
            "Zhuang": 0,
            "Zulu": 0,
            "isiXhosa": 0,
            "isiZulu": 0
        },
        "continent":{
            "Africa": 0,
            "Asia": 0,
            "Australia": 6,
            "Europe": 10,
            "North America": 10,
            "Oceania": 6,
            "South America": 8
        }
    },
    "weather": {    
        "annual_rainy_days": {
            0: 4,
            30: 8,
            60: 10,
            90: 8,
            120: 6,
            150: 4,
            180: 2,
            210: 0,
            240: 0,
            270: 0.,
            300: 0
        },
        "annual_snow_days": {
            0: 6,
            5: 10,
            10: 10,
            15: 8,
            20: 6, 
            25: 4,
            30: 2,
            35: 0,
            40: 0,
            45: 0,
            50: 0 
        },
        "cold_month":{
            "January": 0,
            "February": 0,
            "March": 0,
            "April": 0,
            "May": 0,
            "June": 0,
            "July": 0,
            "August": 0,
            "September": 0,
            "October": 0,
            "November": 0,
            "December": 0
        },
        "cold_month_ave_low_temp": {
            -20: 0,
            -10: 2,
            -0: 4,
            10: 6,
            20: 8,
            30: 10,
            40: 8,
            50: 6,
            60: 4,
            70: 2,
            80: 0
        },
        "cold_month_ave_high_temp": {
            0: 0,
            10: 2,
            20: 4,
            30: 6,
            40: 8,
            50: 10,
            60: 5,
            70: 0,
            80: 0,
            90: 0
        },
        "hot_month":{
            "January": 0,
            "February": 0,
            "March": 0,
            "April": 0,
            "May": 0,
            "June": 0,
            "July": 0,
            "August": 0,
            "September": 0,
            "October": 0,
            "November": 0,
            "December": 0
        }, 
        "hot_month_ave_low_temp":{
            -10: 0,
            0: 0,
            10: 0,
            20: 2,
            30: 4,
            40: 6,
            50: 8,
            60: 10,
            70: 6,
            80: 3,
            90: 0
        }, 
        "hot_month_ave_high_temp":{
            0: 0,
            25: 0,
            50: 0,
            55: 0,
            60: 0,
            65: 2,
            70: 4,
            75: 6,
            80: 8,
            85: 10,
            90: 6,
            95: 3
        }       
    }, 
    "government": {
        "basis_of_legitimacy": {
            "MartialLaw": 0,
            "AbsoluteMonarchy": 0,
            "ParliamentaryConfidence": 10,
            "ParallelMonarchy": 8,
            "NoConstitution": 0,
            "SingleParty": 0,
            "SemiPresidential": 3,
            "Presidential": 1,
            "LegislatureAppointPresident": 3,
            "ChineseGov": 0
        },
        "constitutional_form": {
            "Absolute monarchy": 0,
            "Constitutional monarchy": 5,
            "Provisional": 0,
            "Republic": 10
        },
        "head_of_state": {
            "Ceremonial": 10,
            "Collective": 0,
            "Executive": 2,
            "N/A": 0,
        },
        "health_system": {
            "OOP": 0,
            "PHI": 3,
            "SHI": 6,
            "GHI": 10,
        },
        "laws_firearms": {
            "handguns": {
                "No": 10,
                "Restricted": 7,
                "Yes": 0
            },
            "long_guns": {
                "No": 10,
                "Restricted": 7,
                "Yes": 0,
            },
            "automatics": {
                "No": 10,
                "Restricted": 3,
                "Yes": 0
            },
            "open_carry":{
                "No": 10,
                "Maybe": 3,
                "Restricted": 3,
                "Yes": 0
            },
            "concealed_carry":{
                "No": 10,
                "Restricted": 7,
                "Yes": 0,
            },
            "registration": {
                "Yes": 10,
                "No": 0
            },
        }, 
        "laws_abortion": {
            "risk_to_life": {
                "Prohibited": 0,
                "1": 0,
                "2": 0,
                "3": 0,
                "4": 0,
                "5": 0,
                "6": 0,
                "7": 0,
                "8": 0,
                "9": 0,
                "10": 0,
                "11": 0,
                "12": 0,
                "13": 0,
                "14": 2,
                "15": 2,
                "16": 2,
                "17": 2,
                "18": 4,
                "19": 4,
                "20": 4,
                "21": 4,
                "22": 6,
                "23": 6,
                "24": 6,
                "25": 6,
                "26": 8,
                "27": 8,
                "28": 8,
                "29": 8,
                "30": 10,
                "31": 10,
                "32": 10,
                "33": 10,
                "34": 10,
                "35": 10,
                "Permitted": 10
            },
            "risk_to_health": {
                "Prohibited": 0,
                "1": 0,
                "2": 0,
                "3": 0,
                "4": 0,
                "5": 0,
                "6": 0,
                "7": 0,
                "8": 0,
                "9": 0,
                "10": 0,
                "11": 0,
                "12": 0,
                "13": 0,
                "14": 2,
                "15": 2,
                "16": 2,
                "17": 2,
                "18": 4,
                "19": 4,
                "20": 4,
                "21": 4,
                "22": 6,
                "23": 6,
                "24": 6,
                "25": 6,
                "26": 8,
                "27": 8,
                "28": 8,
                "29": 8,
                "30": 10,
                "31": 10,
                "32": 10,
                "33": 10,
                "34": 10,
                "35": 10,
                "Permitted": 10
            },
            "rape": {
                "Prohibited": 0,
                "1": 0,
                "2": 0,
                "3": 0,
                "4": 0,
                "5": 0,
                "6": 0,
                "7": 0,
                "8": 0,
                "9": 0,
                "10": 0,
                "11": 0,
                "12": 0,
                "13": 0,
                "14": 2,
                "15": 2,
                "16": 2,
                "17": 2,
                "18": 4,
                "19": 4,
                "20": 4,
                "21": 4,
                "22": 6,
                "23": 6,
                "24": 6,
                "25": 6,
                "26": 8,
                "27": 8,
                "28": 8,
                "29": 8,
                "30": 10,
                "31": 10,
                "32": 10,
                "33": 10,
                "34": 10,
                "35": 10,
                "Permitted": 10
            },
            "fetal_impairment": {
                "Prohibited": 0,
                "1": 0,
                "2": 0,
                "3": 0,
                "4": 0,
                "5": 0,
                "6": 0,
                "7": 0,
                "8": 0,
                "9": 0,
                "10": 0,
                "11": 0,
                "12": 0,
                "13": 0,
                "14": 2,
                "15": 2,
                "16": 2,
                "17": 3,
                "18": 3,
                "19": 4,
                "20": 4,
                "21": 4,
                "22": 5,
                "23": 5,
                "24": 5,
                "25": 5,
                "26": 6,
                "27": 6,
                "28": 6,
                "29": 6,
                "30": 10,
                "31": 10,
                "32": 10,
                "33": 8,
                "34": 8,
                "35": 8,
                "Permitted": 10
            },
            "economic_social": {
                "Prohibited": 0,
                "1": 0,
                "2": 0,
                "3": 0,
                "4": 0,
                "5": 0,
                "6": 0,
                "7": 0,
                "8": 0,
                "9": 0,
                "10": 0,
                "11": 0,
                "12": 0,
                "13": 0,
                "14": 2,
                "15": 2,
                "16": 2,
                "17": 3,
                "18": 3,
                "19": 4,
                "20": 4,
                "21": 4,
                "22": 5,
                "23": 5,
                "24": 5,
                "25": 5,
                "26": 6,
                "27": 6,
                "28": 6,
                "29": 6,
                "30": 10,
                "31": 10,
                "32": 10,
                "33": 8,
                "34": 8,
                "35": 8,
                "Permitted": 10
            },
            "on_request": {
                "Prohibited": 0,
                                "1": 0,
                "2": 0,
                "3": 0,
                "4": 0,
                "5": 0,
                "6": 0,
                "7": 0,
                "8": 0,
                "9": 0,
                "10": 0,
                "11": 0,
                "12": 0,
                "13": 0,
                "14": 2,
                "15": 2,
                "16": 2,
                "17": 2,
                "18": 4,
                "19": 4,
                "20": 4,
                "21": 4,
                "22": 6,
                "23": 6,
                "24": 6,
                "25": 6,
                "26": 8,
                "27": 8,
                "28": 8,
                "29": 8,
                "30": 10,
                "31": 10,
                "32": 10,
                "33": 10,
                "34": 10,
                "35": 10,
                "Permitted": 10
            },
        },                       
        "laws_lgbt": {
            "same_sex_sexual_activity": {
                "Death": -10,
                "Illegal": 0,
                "Mixed": 0,
                "Legal": 10
            },
            "same_sex_unions": {
                "Ban": 0,
                "No": 0,
                "Regional": 4,
                "Some": 4,
                "Foreign": 6,
                "Yes": 10
            },
            "same_sex_marriage": {
                "Ban": 0,
                "No": 0,
                "Foreign": 5,
                "Yes": 10
            },
            "same_sex_adoption": {
                "Ban": 0,
                "No": 0,
                "Regional": 3,
                "Yes": 10
            },
            "open_in_military": {
                "No": 0,
                "Wartime": 2,
                "LGBOnly": 4,
                "Closet": 6,
                "Mixed": 8,
                "No Army": 10,
                "Yes": 10
            },
            "anti_disc_laws":{
                "No": 0,
                "Regional": 2,
                "Some": 6,
                "TransOnly": 6,
                "Yes": 10
            },
            "gender_positive_laws":{
                "Anti": 0,
                "Regional": 0,
                "No": 0,
                "Sterilization": 0,
                "Surgery": 0,
                "Medical": 0,
                "Some": 5,
                "Yes": 10,
                "Excellent": 11
            },
            "no_anti_lgbt_laws": {
                "No": 0,
                "Regional": 5,
                "Yes": 10
            },
        }, 
    }
}

point_weights = {
    "city_stats": { # 80
        "population": 20,
        "lang_1": 15,
        "lang_2": 15, 
        "continent": 30      
        },
    "weather": {    # 60
        "annual_rainy_days": 4,
        "annual_snow_days": 8,
        "cold_month": 0,
        "cold_month_ave_low_temp": 12,
        "cold_month_ave_high_temp": 12,
        "hot_month": 0, 
        "hot_month_ave_low_temp": 12, 
        "hot_month_ave_high_temp": 12,     
    }, 
    "government": {
        "basis_of_legitimacy": 25, # 80
        "constitutional_form": 25,
        "head_of_state": 30,
        "health_system": 100, # 100
        "laws_firearms": {  # 100
            "handguns": 5,
            "long_guns": 5,
            "automatics": 5,
            "open_carry": 5,
            "concealed_carry": 5,
            "registration": 5,
        }, 
        "laws_abortion": {
            "risk_to_life": 5,
            "risk_to_health": 5,
            "rape": 5,
            "fetal_impairment": 5,
            "economic_social": 5,
            "on_request": 5,
        },                       
        "laws_lgbt": {
            "same_sex_sexual_activity": 5,
            "same_sex_unions": 5,
            "same_sex_marriage": 5,
            "same_sex_adoption": 5,
            "open_in_military": 5,
            "anti_disc_laws": 5,
            "gender_positive_laws": 5,
            "no_anti_lgbt_laws": 5,
        }
    }
}
