from collections import defaultdict as dd


default_val = object()

Resources = dd(lambda: default_val, {
                "Population" : ["http://simplemaps.com/data/world-cities", 
                                "https://public.opendatasoft.com/explore/dataset/geonames-all-cities-with-a-population-1000/"]
    })
parameters = dd(lambda: default_val, {
              "Name": "String",  
              "Country": "String",
              "Population": [100000,                         
                             200000, 
                             300000, 
                             400000, 
                             500000, 
                             600000, 
                             700000, 
                             800000, 
                             900000,
                             1000000, 
                             1250000, 
                             1500000, 
                             1750000, 
                             2000000, 
                             2500000,
                             3000000, 
                             4000000,
                             5000000,
                             6000000, 
                             7000000, 
                             8000000, 
                             9000000, 
                             10000000],
              "Population Year": "Integer", 
              "Healthcare": ["Universal",
                             "Single Payer", 
                             "Two-Tier", 
                             "Insurance Mandate", 
                             "None"],
              "Annual Hot Month": [01,02,03,04,05,06,07,08,09,10,11,12],
              "Hot Temp": "float", 
              "Annual Cold Month": [01,02,03,04,05,06,07,08,09,10,11,12],
              "Cold Temp": "float", 
              "Annual Average Temp": "float",
              "Language": ["languages"], 
              "Head of State": ["Ceremonial", 
                                "Executive"], 
              "Gun Laws": ["Hunting and sport", 
                           "Personal Protection", 
                           "Open Carry", 
                           "Concealed Carry", 
                           "Without Permit", 
                           "Background Check", 
                           "Registration"], 
              "Region": ["North America", 
                         "Central America", 
                         "South America", 
                         "North Africa", 
                         "Sub-Saharan Africa", 
                         "Southern Africa", 
                         "East Asia", 
                         "Southeast Asia", 
                         "South Asia", 
                         "Central Asia", 
                         "Siberia and Far East", 
                         "Eastern Europe", 
                         "Western Europe", 
                         "Mediterranean Europe", 
                         "Andean South America", 
                         "Southern Cone", 
                         "Brazil"], 
              "Abortion": ["On Request", 
                           "Broad Social/Financial Grounds", 
                           "Preserve Health", 
                           "Save Mother's Life", 
                           "Entirely Prohibited"], 
              "LGBT": ["Same Sex Sexual Activity", 
                       "Same Sex Marriage", 
                       "Same Sex Unions", 
                       "Adoption", 
                       "Military", 
                       "Anti Discrimination Laws", 
                       "Legal Gender Change"],
              "Global Rights Index": "Integer"})

